### ISSUE TITLE
Para Daniel.....

### ISSUE THREAD

**Issue by tonkepen100** [expilu/sailaway-api-to-nmea#1]
Hola daniel , mi mas sincera enhorabiena por el programita. Sensacional y gracias.

Aqui viene el reto... Imaginatelo metido en una rasperry, o beaglebone, correria como server continuamente enviando datos a nuestras tablets o pc.

Se podria realizar una version Arm del programa?.

Gracias de nuevo Daniel.

**Comment by expilu** [comment]
Posible es. Ten encuenta que la app es básicamente una ventana que no hace mucho más que recopilar los datos de la api de Sailaway (usuario, barco, posición, etc,...) y usar el NMEA server, que es una DLL que también tengo en Github https://github.com/expilu/nmea-server

Quizá con Mono o usando la DLL de alguna otra forma se pueda hacer una app nativa para Raspberry.

**Comment by tonkepen100** [comment]
Dani; sabrias hacerlo?, si fuera asi, estaria encantado en pagarte el trabajo.

Abrazos.
