### ISSUE TITLE
Dead reckoning error

### ISSUE THREAD

**Issue by cristi-neagu** [expilu/sailaway-api-to-nmea#5]
Hello,

Looks like the dead reckoning calculator is using the magnetic course instead of the course over ground to calculate a new position.

Thank you.

**Comment by expilu** [comment]
Might be as you say. I just used the heading the API is providing. I'll check if it is magnetic or cog.

**Comment by expilu** [comment]
@cristi-neagu Fixed.

It will be available for the next release, which will be v1.1
